### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rumia163** [qaz1qazlol2/BlueArchivesCraftModpack#2]
### 发生了什么？

商店任务中，钓鱼佬和头盔兑换商店，钓鱼佬不可重复，头盔无需提交即可兑换

### 确认项

- [X] 我已经搜索过了现有的issue，确信这个问题是新的。
- [X] 我已经阅读了说明文档。

### 受影响的版本

1.5.6

**Comment by qaz1qazlol2** [comment]
钓鱼佬不可重复兑换是sf要求的，这个不修复
头盔这个任务会重置的，1.6会对任务进行大幅度重置，耐心等待吧

**Comment by qaz1qazlol2** [comment]
fixed
https://github.com/qaz1qazlol2/BlueArchivesCraftModpack/commit/62784f3d77cc0d84b563a80fd6a79a1f4391f039

**Comment by qaz1qazlol2** [comment]
1.6版本更新后修复
